services:
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.dev.web
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../__tests__:/app/__tests__
      - ../cypress:/app/cypress
      - ../package.json:/app/package.json
      - ../next.config.ts:/app/next.config.ts
      - ../tsconfig.json:/app/tsconfig.json
      - ../tailwind.config.ts:/app/tailwind.config.ts
      - ../postcss.config.mjs:/app/postcss.config.mjs
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - WATCHPACK_POLLING=true
    command: yarn dev
    restart: unless-stopped
    networks:
      - area-network

networks:
  area-network:
    driver: bridge
